### ISSUE TITLE
Add "Pub. L." shorthand for public law

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#1]
`Pub. L. 92-552`
      https://import.ecfr.criticaljuncture.org/on/2021-05-27/title-50/chapter-I/subchapter-F/part-82/section-82.2
 
`Pub. L. 95-134, amended by Pub. L. 95-348, Pub. L. 96-205, Pub. L. 98-213, and Pub. L. 98-454`
      https://import.ecfr.criticaljuncture.org/on/2021-05-27/title-50/chapter-I/subchapter-F/part-84#p-84.46(b)

**Comment by rushed** [comment]
pattern is there, but links aren't wired for prior to 104th Congress (logic pre-dates extraction)

**Comment by rushed** [comment]
examples fail when linked ex: https://www.govinfo.gov/link/plaw/92/public/552 so the pre-extraction restriction seems valid, closing
