### ISSUE TITLE
HTML awareness

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#11]
Currently, for performance reasons the hyperlinker used in renderer had its HTML-awareness removed; it replaces text all in a single pass, and assumes there are no pre-existing links. This generally works ok, but has led to bugs in the past, and means that we need to have [cheesy skip logic](https://github.com/criticaljuncture/reference_parser/blob/main/lib/reference_parser/url.rb#L15-L17) to prevent linking up the src attribute of existing images. This logic obviously doesn't belong in the Gem; and while in the short-term we may want to make an option to ignore URLs that match a certain pattern (so the reference_parser doesn't need to know about Settings), if we can it actually be aware of HTML that would be better.

The auto_link gem has a [basic regexp check](https://github.com/tenderlove/rails_autolink/blob/master/lib/rails_autol
ink/helpers.rb#L141) to look ahead and behind the match to see if between `<` and `>` or  if the last `<a>` in the area before match isn't closed.

I imagine we could do a simpler check where we look only behind, and look to see if the number of `<` equals the number of `>` (ie we aren't inside a tag) and that the number of `<a\b` tags matches the number of `</a>` closing tags (ie we aren't inside a link already). Rather than looking back to the beginning with each match, we could add a `(?<pre_match>.*?)` capture before the match, and add the four counts of what is in there (number of `<`, `>`, `<a\b`, and `</a>`) to a running total that we could use. I imagine this would be faster, as each match would only be looking back through the text since the last match, but 🤷 ...

This approach, if faster, should work for valid XML that has neither comments (`<!-- <<<<< -->`) nor CDATA (`<![CDATA[ <<<<<<< ]]>` tags. I'm not certain if the existing `auto_link` gem works properly in such cases.

The [rinku](https://github.com/vmg/rinku) replacement for auto_link is written in C, which I suspect is more than we wish to bite off.

We'd probably want this as an option to opt-in to.

**Comment by rushed** [comment]
merged in https://github.com/criticaljuncture/reference_parser/commit/04bb9be419833637112ae114edc9539c4a45161f
