### ISSUE TITLE
Add url_spec, remove `Settings` reference and support ignoring URLs

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#12]
- [x] let's remove the reference to [Settings.cloudfront_fr_image_url](https://github.com/criticaljuncture/reference_parser/blob/main/lib/reference_parser/url.rb#L15-L18) and instead make an option when hyperlinking. Then ecfr-renderer could call it with something like:
```
ReferenceParser.new(
  options: {
    url: {
      ignore: -> (x) {url.starts_with?(Settings.cloudfront_fr_image_url)}
    }
  }
)
```
- [x] Let's add a basic `url_spec` that exercises this and some of the other existing features; would be good to include some of the examples from [here](https://github.com/criticaljuncture/ecfr-renderer/blob/main/spec/lib/hyperlinker_spec.rb#L17-L47) and [here](https://github.com/criticaljuncture/federalregister-web/blob/main/spec/lib/hyperlinker/url_spec.rb)

**Comment by rushed** [comment]
some html aware specs left disabled after transfer
