### ISSUE TITLE
Don't link up explicitly reserved items

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#14]
`§§ 462.43-462.44 [Reserved]`
    https://import.ecfr.criticaljuncture.org/on/2021-05-28/title-34/subtitle-B/chapter-IV/part-462

`§§ 240.3a4-2-240.3a4-6 [Reserved]`
  https://import.ecfr.criticaljuncture.org/current/title-17/chapter-II/part-240/subpart-A/#240.3a4-2---240.3a4-6

**Comment by rushed** [comment]
updated for section header case
