### ISSUE TITLE
Section X.Y of Z

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#26]
### Context

Miriam from OFR [flagged](https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/112711169/comments) [16 CFR 1450.3](https://www.ecfr.gov/current/title-16/chapter-II/subchapter-B/part-1450/section-1450.3):

![image](https://user-images.githubusercontent.com/27157/135882318-ab1f908a-aa6b-4555-8eaa-efa6c00278e4.png)

Where we're linking up text like `Section 9.4 of ANSI/APSP/ICC-16 2017`

Is it possible to not link up references that end with "of Z" when Z doesn't represent a portion of the CFR?

**Comment by rushed** [comment]
This is currently done via an excluding regex which I’ve updated for the flagged section. Let me know if you’d like to see something stricter.

https://github.com/criticaljuncture/reference_parser/blob/main/lib/reference_parser/cfr.rb#L308



![Screen Shot 2021-10-04 at 11 13 15 AM](https://user-images.githubusercontent.com/14638/135888665-349b23c7-7cd9-4e53-918d-5be840ff6ff5.png)

**Comment by rushed** [comment]
merged in https://github.com/criticaljuncture/reference_parser/commit/923edad6801179fd0fe30c94585f8f45c423b675
