### ISSUE TITLE
hyperlink error in section+paragraph reference

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#27]
in [21 CFR 201.66](https://www.ecfr.gov/on/2020-09-11/title-21/chapter-I/subchapter-C/part-201/subpart-C/section-201.66#p-201.66(c)(5)(ii)(C)), in this text `§§ 341.74(c)(5)(iii), 344.52(c), 358.150(c), and 358.550(c) of this chapter`, the first link goes to this URL `/on/2020-09-11/title-21/section-341.74(c)(5)(iii)`, which 404s.

**Comment by rushed** [comment]
merged in https://github.com/criticaljuncture/reference_parser/commit/666e583658b5ea841c83d5782180b957c5d3741e
