### ISSUE TITLE
Improve links on FR citation page ranges

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#28]
Currently when we get FR references like `51 FR 6537-42` (eg [here](https://www.ecfr.gov/current/title-40/chapter-I/subchapter-I/part-271/subpart-A/section-271.1) the resulting link goes to `https://www.federalregister.gov/citation/51-FR-6537-42`, and the data-reference is `51 FR 6537-42`. As these represent page ranges, we should just use the first page of the range as the reference. Interestingly, `59 FR 62896-62953` on the same page seems to work ok.

**Comment by rushed** [comment]
resolved via https://github.com/criticaljuncture/reference_parser/commit/1231ea600e303687fd50731ff75ad0098dfa5201
