### ISSUE TITLE
Handle PGI References

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#29]
### Context

Sometimes the CFR references Defense Federal Acquisition Regulation Supplement (DFARS) and Procedures, Guidance, and Information (PGI)

https://www.acq.osd.mil/dpap/dars/dfarspgi/current/index.html

Sometimes we seem to be linking up those references as if they are CFR references, eg [here](https://www.ecfr.gov/current/title-48/chapter-2/subchapter-C/part-215/subpart-215.4/section-215.404-2). Let's either ignore them or link them to the proper location. For whatever reason, seeing this a lot with PGI references but not DFARS.

**Comment by rushed** [comment]
resolved via https://github.com/criticaljuncture/reference_parser/commit/7b441c95b6677fdce034f0996f991fac981f0c60
