### ISSUE TITLE
Dropping of "Pub L." in 17 CFR 230

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#30]
### Context

in [17 CFR 230](https://www.ecfr.gov/current/title-17/chapter-II/part-230) the "Pub L. 112-206" is dropped from the Authority text:

![image](https://user-images.githubusercontent.com/27157/151850834-4bb3bb33-b0d5-4bf5-8e08-398a0bf590ca.png)
![image](https://user-images.githubusercontent.com/27157/151851062-884cf6a5-92aa-4366-b471-c532bf67be5f.png)

**Comment by rushed** [comment]
Dropped text no longer reproduces, additional tests and improved list handling for example added in 737d95e05091517152843f6614e52c9a33c5a996

![Screen Shot 2022-01-31 at 10 19 30 PM](https://user-images.githubusercontent.com/14638/151912286-f06adbad-8dc2-404a-a26c-b0f76e19715e.png)

**Comment by andrewcarpenter** [comment]
Let's also double check [13 CFR 121](https://www.ecfr.gov/current/title-13/chapter-I/part-121) to make sure it would be fixed in the next reprocess.

**Comment by rushed** [comment]
Known cases appear resolved on prod
