### ISSUE TITLE
CFR Reference partially linked up when matching current section

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#31]
### Context

OFR [reports](https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/113219343/comments) that in [49 CFR 192.7(j)(1)](https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-192/subpart-A/section-192.7#p-192.7(j)(1)) we're linking up a fragment of a larger CFR reference:

![image](https://user-images.githubusercontent.com/27157/153485808-75f08273-bc8b-432e-961a-8920dfd0c427.png)

Perhaps we need an end anchor (perhaps a negative lookahead to hypen, number, or letter) at the end of the match for the current section identifier?

**Comment by rushed** [comment]
resolved in c1ee904025a9644e378ca45b612e9394b60ddb4f
