### ISSUE TITLE
Semicolon-separated references not being linked up

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#32]
### Context

OFR [reports](https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/113219343/comments) that in [49 CFR 192.7](https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-192/subpart-A/section-192.7) there are multiple CFR references separated by a semicolon. Let's explore how many false positives we might end up with if we expand to support semi-colon separated references.

Definitely lower priority -- this seems like an odd way to make a list to me.

**Comment by rushed** [comment]
resolved in 281be2a
