### ISSUE TITLE
Over-aggressive hyperlinking of section reference

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#33]
### Context

A user reports that in an [incorporation by reference section](https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-193/subpart-I), we see to be errantly assuming a section reference is a CFR reference:

`[section 9.9](https://www.ecfr.gov/current/title-49/section-9.9) of NFPA-59A-2001`

also seems to affect a number of other areas within [49 CFR 193](https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-193)

**Comment by rushed** [comment]
resolved via b680996
