### ISSUE TITLE
Incorrect reference links in 21 CFR 101.2(b)

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#36]
A user [reports](https://ofr.zendesk.com/agent/tickets/41021) that in [21 CFR 101.2(b)](https://www.ecfr.gov/current/title-21/chapter-I/subchapter-B/part-101#p-101.2(b)), all the links up to and including 101.36 in

> [§§ 101.4](https://www.ecfr.gov/current/title-21/section-1.36), [101.5](https://www.ecfr.gov/current/title-21/section-1.36), [101.8](https://www.ecfr.gov/current/title-21/section-1.36), [101.9](https://www.ecfr.gov/current/title-21/section-1.36), [101.13](https://www.ecfr.gov/current/title-21/section-1.36), [101.17](https://www.ecfr.gov/current/title-21/section-1.36), [101.36](https://www.ecfr.gov/current/title-21/section-1.36), [subpart D of part 101](https://www.ecfr.gov/current/title-21/part-101/subpart-D)

errantly go to section 1.36 (not even 101.36).

Also seems to be happening in [21 CFR 101.2(f)](https://www.ecfr.gov/current/title-21/chapter-I/subchapter-B/part-101#p-101.2(f))

**Comment by rushed** [comment]
previously addressed in https://github.com/criticaljuncture/reference_parser/issues/34
21/101.13 re-generated on prod and appearing as expected
