### ISSUE TITLE
"Subsection 38.3" Linking

### ISSUE THREAD

**Issue by brandon-carag** [criticaljuncture/reference_parser#38]
### Description
We received the following user report:

```
Bad hyperlink under 175.10 (a)(19).

"Each lithium battery must be of a type which meets the requirements of each test in the UN Manual of Tests and Criteria, Part III, Subsection 38.3. Recharging of the devices and/or the batteries on board the aircraft is not permitted. Each installed or spare lithium battery: "
```

The user appears to have been referring to this page: https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-175#p-175.10(a)(16)(iv)

**Screenshots**
![Screen Shot 2023-01-19 at 4 08 55 PM](https://user-images.githubusercontent.com/3423367/213589542-6696e8ba-50fa-4a24-9df8-d8bf9409c57e.png)

Not sure whether this is avoidable or not but wanted to surface the report in case.

**Comment by rushed** [comment]
resolved via 58027e015d82f42334a986aa52c7fc2660c95637
