### ISSUE TITLE
Broken Link when only Subpart Present

### ISSUE THREAD

**Issue by brandon-carag** [criticaljuncture/reference_parser#40]
Not high priority, but we received the following user report re: a bad link reference:

"The link to 48 CFR subpart 2.1 on (https://www.ecfr.gov/current/title-2/subtitle-B/chapter-XI/subchapter-A/part-1108/subpart-B/section-1108.340) is broken"

**Comment by rushed** [comment]
#### generated:
`https://www.ecfr.gov/current/title-48/part-/subpart-2.1`
#### expected (either would land):
`https://www.ecfr.gov/current/title-48/subpart-2.1`
`https://www.ecfr.gov/current/title-48/part-2/subpart-2.1`

**Comment by rushed** [comment]
resolved via feaca81
