### ISSUE TITLE
U.S.C. References with Letter-based Suffixes

### ISSUE THREAD

**Issue by brandon-carag** [criticaljuncture/reference_parser#41]
Context: We received the following user report:

```The link to the recompete areas is broken. This seems pretty important given the whole point is to ask people for feedback on how to equitably distribute this program.```

The page referenced is here: https://www.federalregister.gov/documents/2023/02/23/2023-03732/request-for-information-on-implementation-of-the-distressed-area-recompete-pilot-program#addresses

![Screen Shot 2023-03-02 at 10 29 02 AM](https://user-images.githubusercontent.com/3423367/222519334-4b98bb28-570d-4865-83e8-25e60ad9eafb.png)

"15 U.S.C. 3722b" appears to link to https://www.govinfo.gov/link/uscode/15/3722b .  It seems like govinfo may not support letter-based suffixes because https://www.govinfo.gov/link/uscode/15/3722 seems to work

**Comment by rushed** [comment]
These similar examples land on distinct pages:
https://www.govinfo.gov/link/uscode/15/77
https://www.govinfo.gov/link/uscode/15/77f

https://www.govinfo.gov/link/uscode/5/552
https://www.govinfo.gov/link/uscode/5/552a

https://www.govinfo.gov/link/uscode/16/470
https://www.govinfo.gov/link/uscode/16/470s

The section quoted is potentially newer then would be expected to appear?
https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title15-section3722b&num=0&edition=prelim
