### ISSUE TITLE
"§ 264.15(b) of this part" Style References

### ISSUE THREAD

**Issue by brandon-carag** [criticaljuncture/reference_parser#43]
Context: We received the following user report:

"40 CFR 270.14(b)(5) the link in this section to 40 CFR 264.15(b) does not work."

This looks to be the source URL; I've highlighted the reference the user's referring to in the screenshot below.

https://www.ecfr.gov/current/title-40/chapter-I/subchapter-I/part-270#270.14

![Screen Shot 2023-03-21 at 9 22 31 AM](https://user-images.githubusercontent.com/3423367/226674131-47013a52-5898-44c3-9213-6828e541eb4f.png)

**Comment by andrewcarpenter** [comment]
IMO the "by § 264.15(b) of this part" (when in part 270) is ok enough generating a bad URL, as there isn't a section 264.15 in part 270.

However, the other links in that paragraph  -- 270.14(b)(5) -- seem more wrong.

**Comment by rushed** [comment]
resolved via 32fa232d143c0e51c3b1104220e7c11df0d0dbab
