### ISSUE TITLE
Consider linking paragraph references without the word paragraph

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/reference_parser#6]
at least if they end with "of this section"

`Except for payments subject to the increased payment limitation in (e)(2)(ii) and (e)(2)(iii) of this section`
    https://import.ecfr.criticaljuncture.org/on/2021-05-27/title-7/subtitle-A/part-9#p-9.7(e)(3)(i)

**Comment by rushed** [comment]
"of this section" case added
